### ISSUE TITLE
Support Casbin as the authorization module

### ISSUE THREAD

**Issue by hsluoyz** [skypika/GoWeb#1]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security than the current RBAC. I can make PR if needed. Let me know if there's any question:) Thanks.

**Comment by hunterhug** [comment]
不好意思，该项目已经实现了RBAC，基于beego框架
这是一个为了开发网站比较快的项目，并不需要太多种方式的权限认证。
你说的我都懂，ACL，RBAC，ABAC，粒度不一样而已。

但是请首先出一个中文的说明文档，中国开发者数量庞大！
