### ISSUE TITLE
报错了 这个是什么情况

### ISSUE THREAD

**Issue by anigm** [skypika/GoWeb#2]
./main.go:46: cannot use controllers.ErrorController literal (type *controllers.ErrorController) as type "tuzi/vendor/github.com/astaxie/beego".ControllerInterface in argument to "tuzi/vendor/github.com/astaxie/beego".ErrorController:
        *controllers.ErrorController does not implement "tuzi/vendor/github.com/astaxie/beego".ControllerInterface (wrong type for Init method)
                have Init(*"github.com/hunterhug/GoWeb/vendor/github.com/astaxie/beego/context".Context, string, string, interface {})
                want Init(*"tuzi/vendor/github.com/astaxie/beego/context".Context, string, string, interface {})
2017/07/18 18:03:00 ERROR    ▶ 0003 Failed to build the application: # tuzi
./main.go:46: cannot use controllers.ErrorController literal (type *controllers.ErrorController) as type "tuzi/vendor/github.com/astaxie/beego".ControllerInterface in argument to "tuzi/vendor/github.com/astaxie/beego".ErrorController:
        *controllers.ErrorController does not implement "tuzi/vendor/github.com/astaxie/beego".ControllerInterface (wrong type for Init method)
                have Init(*"github.com/hunterhug/GoWeb/vendor/github.com/astaxie/beego/context".Context, string, string, interface {})
                want Init(*"tuzi/vendor/github.com/astaxie/beego/context".Context, string, string, interface {})

**Comment by hunterhug** [comment]
把vendor下的包移走
